version: '3.8'

services:
  tg-bot-monitor:
    build: .
    container_name: tg-bot-monitor
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_USER_CHAT_ID=${TG_USER_CHAT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow access to Docker socket for monitoring other containers
      - /proc:/host_proc # Allow access to system information from the host
    restart: unless-stopped
    networks:
      - tg-bot-monitor-network # Define a network if needed

networks:
  tg-bot-monitor-network:
    driver: bridge
